# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e9964e72ae28c9119c33682f851e43dc2a0ca8f3b75503033e9c56ea0b8163e3f3e7223e492d65688c73a1d2c36238f12d5952e2ad1b194f991802e0cd93858

test:
  secret_key_base: 53ea52ec3539d474422d12041aa278acf9c42292d9edb281d59166f480d29eea732ce7b6898917e4eddf53f60cd915e1c89f934c00d7fcfa77e6422669da904d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
